### ISSUE TITLE
Store co-contents in content/

### ISSUE THREAD

**Issue by cmb69** [cmb69/coco_xh#1]
The co-contents should be stored in the general content/ folder by default. Perhaps the resp. config option should be removed.

**Comment by Kao64** [comment]
Problem with co-content plugin. If you've a page like this (exemple in french) "L'égalité" it generate a bug in front view, the next page have the same content and it is impossible to insert new co content, or update co-content. I think it's a problem with text encoding and special caracters like ' and " .
Could you please update this please thanks.

**Comment by cmb69** [comment]
@Kao64 I have already replied to your request in cmsimpleforum.com. I've you prefer to discuss this on Github, please create a _new issue_.
